### PR TITLE
Add in prettier config.

### PR DESCRIPTION
**Pull request by alekhinen**
Since we're standardizing on prettier, let's have a single source of truth for the configuration of it.

### CODE REVIEW

**Review by dylanpyle — APPROVED** [review]
looks great 2 me

**Comment by dylanpyle** [comment]
@alekhinen I guess one more thought - we could add the prettier CLI itself and the `format`/`test-format` scripts around it to this repo, so that we'd also be standardizing on one version etc. your call.

**Comment by alekhinen** [comment]
@dylanpyle sure, the scripts currently live in `package.json` app files like so:
```
"format": "prettier \"src/**/*.ts\" --write",
```

```
"test-format": "prettier \"src/**/*.ts\" -l",
```

Is it even possible to expose this package's scripts to apps that consume this package?

**Comment by alekhinen** [comment]
@dylanpyle not sure if this will work but e9626e5

**Comment by alekhinen** [comment]
I'm deeming this not worth further exploration right now as we are under a time crunch to get another project out.

**Pull request closed without merging**
